[package]
name = "me-frp_desktop_unoffical"
version = "2.2.0"
description = "ME-FrpXLDesktop"
authors = ["yealqp"]
edition = "2021"

[lib]
name = "me_frp_desktop_unoffical_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5", features = [] }

[dependencies]
tauri = { version = "2.10", features = [ "tray-icon"] }
tauri-plugin-opener = "2.5"
tauri-plugin-fs = "2.5"
tauri-plugin-single-instance = "2.3"
tauri-plugin-autostart = "2.1"

serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
reqwest = { version = "0.13", features = ["json", "gzip", "brotli", "deflate"] }
urlencoding = "2.1"
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
tauri-plugin-dialog = "2.7.0"
base64 = "0.22.1"

